// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvSNNZQNfugAdNXiHxNz-zssZu6y0YQOI',
    appId: '1:1000418691417:web:386487f3c51d3662b0a448',
    messagingSenderId: '1000418691417',
    projectId: 'smart-shop-b12b0',
    authDomain: 'smart-shop-b12b0.firebaseapp.com',
    storageBucket: 'smart-shop-b12b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJPUF_sUuOdAeuXbetDqFxqz4KKy4I_4',
    appId: '1:1000418691417:android:a916a35badcc6951b0a448',
    messagingSenderId: '1000418691417',
    projectId: 'smart-shop-b12b0',
    storageBucket: 'smart-shop-b12b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl6QPO5gOpD-L8SbKc0359B1yCS2u6Smw',
    appId: '1:1000418691417:ios:33706fafb630e868b0a448',
    messagingSenderId: '1000418691417',
    projectId: 'smart-shop-b12b0',
    storageBucket: 'smart-shop-b12b0.appspot.com',
    iosBundleId: 'com.example.smartShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl6QPO5gOpD-L8SbKc0359B1yCS2u6Smw',
    appId: '1:1000418691417:ios:f8bff438722e2a7fb0a448',
    messagingSenderId: '1000418691417',
    projectId: 'smart-shop-b12b0',
    storageBucket: 'smart-shop-b12b0.appspot.com',
    iosBundleId: 'com.example.smartShop.RunnerTests',
  );
}
